### ISSUE TITLE
[Feature Request/Discussion] Discussing/deciding on how emojis will appear in the NB interface

### ISSUE THREAD

**Issue by hglokim** [haystack/nbclient#2]
I saw that when you type in a hashtag, the associated emoji will show up -- this is pretty neat! I'm wondering if there was rationale for not also including the emoji options as clickable icons. We should discuss how we want to display emoji options in the NB interface!

**Comment by karger** [comment]
This is quite a reasonable question or actually a pair:

1) should we have a way to click to insert emoji?  I would think the 
answer should be yes, since this is the standard on many social media 
platforms

2) should emoji be equated to hashtags?  This one is more of a puzzle.   
When we started, we were just using hashtags, which fit naturally as 
words in the text.  when we introduced emoji, we saw this natural 
association between emoji and hashtags.  And it's really nice to have 
the emoji because they are more visual/good for scanning and quick 
recognition.   On the other hand, it's awkward to just arbitrarily 
substitute an emoji for a hashtag, e.g. "I'm : ) to see you today" is 
*more* complicated to read than the text version.  Emoji can of course 
be placed in a comment, but they then serve as "flavor" rather than part 
of the text, often showing at the end of a sentence.

So how do support these various things, which are sometimes in tension?  
If we offer a click-to-insert-emoji, are we inserting just the emoji or 
are we inserting the hashtag?  The latter would not make sense if the 
emoji was intended only for flavor.  But if we insert *only* the emojy, 
then it breaks when the user intends to insert that hashtag as text.
